CREATE TABLE `Pembenihan` (
    `id`	INT(11) NOT NULL PRIMARY,
    `TAHUN`	INT(4) DEFAULT NULL,
    `PROVINSI`	VARCHAR(512) DEFAULT NULL,
    `JENIS_PEMBENIHAN`	VARCHAR(512) DEFAULT NULL,
    `KAB_KOTA`	VARCHAR(512) DEFAULT NULL,
    `KELOMPOK_IKAN`	VARCHAR(512) DEFAULT NULL,
    `VOLUME`	INT DEFAULT NULL
);

INSERT INTO `Pembenihan` (`id`, `TAHUN`, `PROVINSI`, `JENIS_PEMBENIHAN`, `KAB_KOTA`, `KELOMPOK_IKAN`, `VOLUME`) VALUES ('', '2024', 'KALIMANTAN TIMUR', 'Pembenihan Air Laut', 'BERAU', 'Udang Windu', '3400000');
INSERT INTO `Pembenihan` (`id`, `TAHUN`, `PROVINSI`, `JENIS_PEMBENIHAN`, `KAB_KOTA`, `KELOMPOK_IKAN`, `VOLUME`) VALUES ('', '2024', 'KALIMANTAN TIMUR', 'Pembenihan Air Laut', 'KOTA BALIKPAPAN', 'Kakap', '1000');
INSERT INTO `Pembenihan` (`id`, `TAHUN`, `PROVINSI`, `JENIS_PEMBENIHAN`, `KAB_KOTA`, `KELOMPOK_IKAN`, `VOLUME`) VALUES ('', '2024', 'KALIMANTAN TIMUR', 'Pembenihan Air Laut', 'KOTA BALIKPAPAN', 'Kerapu', '1000');
INSERT INTO `Pembenihan` (`id`, `TAHUN`, `PROVINSI`, `JENIS_PEMBENIHAN`, `KAB_KOTA`, `KELOMPOK_IKAN`, `VOLUME`) VALUES ('', '2024', 'KALIMANTAN TIMUR', 'Pembenihan Air Laut', 'KOTA BALIKPAPAN', 'Udang Windu', '395378000');
INSERT INTO `Pembenihan` (`id`, `TAHUN`, `PROVINSI`, `JENIS_PEMBENIHAN`, `KAB_KOTA`, `KELOMPOK_IKAN`, `VOLUME`) VALUES ('', '2024', 'KALIMANTAN TIMUR', 'Pembenihan Air Laut', 'KUTAI KARTANEGARA', 'Udang Windu', '742320000');
INSERT INTO `Pembenihan` (`id`, `TAHUN`, `PROVINSI`, `JENIS_PEMBENIHAN`, `KAB_KOTA`, `KELOMPOK_IKAN`, `VOLUME`) VALUES ('', '2024', 'KALIMANTAN TIMUR', 'Pembenihan Air Laut', 'PASER', 'Udang Windu', '3294000');
INSERT INTO `Pembenihan` (`id`, `TAHUN`, `PROVINSI`, `JENIS_PEMBENIHAN`, `KAB_KOTA`, `KELOMPOK_IKAN`, `VOLUME`) VALUES ('', '2024', 'KALIMANTAN TIMUR', 'Pembenihan Air Laut', 'PENAJAM PASER UTARA', 'Udang Windu', '15200000');
INSERT INTO `Pembenihan` (`id`, `TAHUN`, `PROVINSI`, `JENIS_PEMBENIHAN`, `KAB_KOTA`, `KELOMPOK_IKAN`, `VOLUME`) VALUES ('', '2024', 'KALIMANTAN TIMUR', 'Pembenihan Air Tawar', 'BERAU', 'Lele', '2049000');
INSERT INTO `Pembenihan` (`id`, `TAHUN`, `PROVINSI`, `JENIS_PEMBENIHAN`, `KAB_KOTA`, `KELOMPOK_IKAN`, `VOLUME`) VALUES ('', '2024', 'KALIMANTAN TIMUR', 'Pembenihan Air Tawar', 'BERAU', 'Mas', '45000');
INSERT INTO `Pembenihan` (`id`, `TAHUN`, `PROVINSI`, `JENIS_PEMBENIHAN`, `KAB_KOTA`, `KELOMPOK_IKAN`, `VOLUME`) VALUES ('', '2024', 'KALIMANTAN TIMUR', 'Pembenihan Air Tawar', 'BERAU', 'Nila', '2126000');
INSERT INTO `Pembenihan` (`id`, `TAHUN`, `PROVINSI`, `JENIS_PEMBENIHAN`, `KAB_KOTA`, `KELOMPOK_IKAN`, `VOLUME`) VALUES ('', '2024', 'KALIMANTAN TIMUR', 'Pembenihan Air Tawar', 'BERAU', 'Patin', '52000');
INSERT INTO `Pembenihan` (`id`, `TAHUN`, `PROVINSI`, `JENIS_PEMBENIHAN`, `KAB_KOTA`, `KELOMPOK_IKAN`, `VOLUME`) VALUES ('', '2024', 'KALIMANTAN TIMUR', 'Pembenihan Air Tawar', 'KOTA BALIKPAPAN', 'Lele', '9678000');
INSERT INTO `Pembenihan` (`id`, `TAHUN`, `PROVINSI`, `JENIS_PEMBENIHAN`, `KAB_KOTA`, `KELOMPOK_IKAN`, `VOLUME`) VALUES ('', '2024', 'KALIMANTAN TIMUR', 'Pembenihan Air Tawar', 'KOTA BALIKPAPAN', 'Nila', '203000');
INSERT INTO `Pembenihan` (`id`, `TAHUN`, `PROVINSI`, `JENIS_PEMBENIHAN`, `KAB_KOTA`, `KELOMPOK_IKAN`, `VOLUME`) VALUES ('', '2024', 'KALIMANTAN TIMUR', 'Pembenihan Air Tawar', 'KOTA BONTANG', 'Gurami', '34000');
INSERT INTO `Pembenihan` (`id`, `TAHUN`, `PROVINSI`, `JENIS_PEMBENIHAN`, `KAB_KOTA`, `KELOMPOK_IKAN`, `VOLUME`) VALUES ('', '2024', 'KALIMANTAN TIMUR', 'Pembenihan Air Tawar', 'KOTA BONTANG', 'Lele', '41000');
INSERT INTO `Pembenihan` (`id`, `TAHUN`, `PROVINSI`, `JENIS_PEMBENIHAN`, `KAB_KOTA`, `KELOMPOK_IKAN`, `VOLUME`) VALUES ('', '2024', 'KALIMANTAN TIMUR', 'Pembenihan Air Tawar', 'KOTA BONTANG', 'Nila', '36000');
INSERT INTO `Pembenihan` (`id`, `TAHUN`, `PROVINSI`, `JENIS_PEMBENIHAN`, `KAB_KOTA`, `KELOMPOK_IKAN`, `VOLUME`) VALUES ('', '2024', 'KALIMANTAN TIMUR', 'Pembenihan Air Tawar', 'KOTA SAMARINDA', 'Gurami', '152000');
INSERT INTO `Pembenihan` (`id`, `TAHUN`, `PROVINSI`, `JENIS_PEMBENIHAN`, `KAB_KOTA`, `KELOMPOK_IKAN`, `VOLUME`) VALUES ('', '2024', 'KALIMANTAN TIMUR', 'Pembenihan Air Tawar', 'KOTA SAMARINDA', 'Lele', '30901000');
INSERT INTO `Pembenihan` (`id`, `TAHUN`, `PROVINSI`, `JENIS_PEMBENIHAN`, `KAB_KOTA`, `KELOMPOK_IKAN`, `VOLUME`) VALUES ('', '2024', 'KALIMANTAN TIMUR', 'Pembenihan Air Tawar', 'KOTA SAMARINDA', 'Mas', '288000');
INSERT INTO `Pembenihan` (`id`, `TAHUN`, `PROVINSI`, `JENIS_PEMBENIHAN`, `KAB_KOTA`, `KELOMPOK_IKAN`, `VOLUME`) VALUES ('', '2024', 'KALIMANTAN TIMUR', 'Pembenihan Air Tawar', 'KOTA SAMARINDA', 'Nila', '1140000');
INSERT INTO `Pembenihan` (`id`, `TAHUN`, `PROVINSI`, `JENIS_PEMBENIHAN`, `KAB_KOTA`, `KELOMPOK_IKAN`, `VOLUME`) VALUES ('', '2024', 'KALIMANTAN TIMUR', 'Pembenihan Air Tawar', 'KOTA SAMARINDA', 'Patin', '1534000');
INSERT INTO `Pembenihan` (`id`, `TAHUN`, `PROVINSI`, `JENIS_PEMBENIHAN`, `KAB_KOTA`, `KELOMPOK_IKAN`, `VOLUME`) VALUES ('', '2024', 'KALIMANTAN TIMUR', 'Pembenihan Air Tawar', 'KUTAI BARAT', 'Lele', '51000');
INSERT INTO `Pembenihan` (`id`, `TAHUN`, `PROVINSI`, `JENIS_PEMBENIHAN`, `KAB_KOTA`, `KELOMPOK_IKAN`, `VOLUME`) VALUES ('', '2024', 'KALIMANTAN TIMUR', 'Pembenihan Air Tawar', 'KUTAI BARAT', 'Mas', '39000');
INSERT INTO `Pembenihan` (`id`, `TAHUN`, `PROVINSI`, `JENIS_PEMBENIHAN`, `KAB_KOTA`, `KELOMPOK_IKAN`, `VOLUME`) VALUES ('', '2024', 'KALIMANTAN TIMUR', 'Pembenihan Air Tawar', 'KUTAI BARAT', 'Nila', '58000');
INSERT INTO `Pembenihan` (`id`, `TAHUN`, `PROVINSI`, `JENIS_PEMBENIHAN`, `KAB_KOTA`, `KELOMPOK_IKAN`, `VOLUME`) VALUES ('', '2024', 'KALIMANTAN TIMUR', 'Pembenihan Air Tawar', 'KUTAI KARTANEGARA', 'Ikan Lainnya', '34185000');
INSERT INTO `Pembenihan` (`id`, `TAHUN`, `PROVINSI`, `JENIS_PEMBENIHAN`, `KAB_KOTA`, `KELOMPOK_IKAN`, `VOLUME`) VALUES ('', '2024', 'KALIMANTAN TIMUR', 'Pembenihan Air Tawar', 'KUTAI KARTANEGARA', 'Lele', '113189000');
INSERT INTO `Pembenihan` (`id`, `TAHUN`, `PROVINSI`, `JENIS_PEMBENIHAN`, `KAB_KOTA`, `KELOMPOK_IKAN`, `VOLUME`) VALUES ('', '2024', 'KALIMANTAN TIMUR', 'Pembenihan Air Tawar', 'KUTAI KARTANEGARA', 'Mas', '100385000');
INSERT INTO `Pembenihan` (`id`, `TAHUN`, `PROVINSI`, `JENIS_PEMBENIHAN`, `KAB_KOTA`, `KELOMPOK_IKAN`, `VOLUME`) VALUES ('', '2024', 'KALIMANTAN TIMUR', 'Pembenihan Air Tawar', 'KUTAI KARTANEGARA', 'Nila', '335457000');
INSERT INTO `Pembenihan` (`id`, `TAHUN`, `PROVINSI`, `JENIS_PEMBENIHAN`, `KAB_KOTA`, `KELOMPOK_IKAN`, `VOLUME`) VALUES ('', '2024', 'KALIMANTAN TIMUR', 'Pembenihan Air Tawar', 'KUTAI KARTANEGARA', 'Patin', '102707000');
INSERT INTO `Pembenihan` (`id`, `TAHUN`, `PROVINSI`, `JENIS_PEMBENIHAN`, `KAB_KOTA`, `KELOMPOK_IKAN`, `VOLUME`) VALUES ('', '2024', 'KALIMANTAN TIMUR', 'Pembenihan Air Tawar', 'KUTAI TIMUR', 'Gurami', '68000');
INSERT INTO `Pembenihan` (`id`, `TAHUN`, `PROVINSI`, `JENIS_PEMBENIHAN`, `KAB_KOTA`, `KELOMPOK_IKAN`, `VOLUME`) VALUES ('', '2024', 'KALIMANTAN TIMUR', 'Pembenihan Air Tawar', 'KUTAI TIMUR', 'Lele', '1020000');
INSERT INTO `Pembenihan` (`id`, `TAHUN`, `PROVINSI`, `JENIS_PEMBENIHAN`, `KAB_KOTA`, `KELOMPOK_IKAN`, `VOLUME`) VALUES ('', '2024', 'KALIMANTAN TIMUR', 'Pembenihan Air Tawar', 'KUTAI TIMUR', 'Mas', '335000');
INSERT INTO `Pembenihan` (`id`, `TAHUN`, `PROVINSI`, `JENIS_PEMBENIHAN`, `KAB_KOTA`, `KELOMPOK_IKAN`, `VOLUME`) VALUES ('', '2024', 'KALIMANTAN TIMUR', 'Pembenihan Air Tawar', 'KUTAI TIMUR', 'Nila', '905000');
INSERT INTO `Pembenihan` (`id`, `TAHUN`, `PROVINSI`, `JENIS_PEMBENIHAN`, `KAB_KOTA`, `KELOMPOK_IKAN`, `VOLUME`) VALUES ('', '2024', 'KALIMANTAN TIMUR', 'Pembenihan Air Tawar', 'KUTAI TIMUR', 'Patin', '92000');
INSERT INTO `Pembenihan` (`id`, `TAHUN`, `PROVINSI`, `JENIS_PEMBENIHAN`, `KAB_KOTA`, `KELOMPOK_IKAN`, `VOLUME`) VALUES ('', '2024', 'KALIMANTAN TIMUR', 'Pembenihan Air Tawar', 'PASER', 'Gurami', '6000');
INSERT INTO `Pembenihan` (`id`, `TAHUN`, `PROVINSI`, `JENIS_PEMBENIHAN`, `KAB_KOTA`, `KELOMPOK_IKAN`, `VOLUME`) VALUES ('', '2024', 'KALIMANTAN TIMUR', 'Pembenihan Air Tawar', 'PASER', 'Lele', '618000');
INSERT INTO `Pembenihan` (`id`, `TAHUN`, `PROVINSI`, `JENIS_PEMBENIHAN`, `KAB_KOTA`, `KELOMPOK_IKAN`, `VOLUME`) VALUES ('', '2024', 'KALIMANTAN TIMUR', 'Pembenihan Air Tawar', 'PASER', 'Nila', '221000');
INSERT INTO `Pembenihan` (`id`, `TAHUN`, `PROVINSI`, `JENIS_PEMBENIHAN`, `KAB_KOTA`, `KELOMPOK_IKAN`, `VOLUME`) VALUES ('', '2024', 'KALIMANTAN TIMUR', 'Pembenihan Air Tawar', 'PENAJAM PASER UTARA', 'Gurami', '9000');
INSERT INTO `Pembenihan` (`id`, `TAHUN`, `PROVINSI`, `JENIS_PEMBENIHAN`, `KAB_KOTA`, `KELOMPOK_IKAN`, `VOLUME`) VALUES ('', '2024', 'KALIMANTAN TIMUR', 'Pembenihan Air Tawar', 'PENAJAM PASER UTARA', 'Lele', '600000');
INSERT INTO `Pembenihan` (`id`, `TAHUN`, `PROVINSI`, `JENIS_PEMBENIHAN`, `KAB_KOTA`, `KELOMPOK_IKAN`, `VOLUME`) VALUES ('', '2024', 'KALIMANTAN TIMUR', 'Pembenihan Air Tawar', 'PENAJAM PASER UTARA', 'Mas', '96000');
INSERT INTO `Pembenihan` (`id`, `TAHUN`, `PROVINSI`, `JENIS_PEMBENIHAN`, `KAB_KOTA`, `KELOMPOK_IKAN`, `VOLUME`) VALUES ('', '2024', 'KALIMANTAN TIMUR', 'Pembenihan Air Tawar', 'PENAJAM PASER UTARA', 'Nila', '444000');
